name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7
    with:
      folders: |
        [
          ".",
          "test/smoke",
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false},
          {"folder": "test/smoke", "bzlmodEnabled": false},
        ]
