name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v6
    permissions:
      contents: write
    with:
      release_files: rules_gazebo-*.tar.gz
      prerelease: false
